depends:
  - supervisord

ports:
  - 8000
  - 8080

service: |
  [program:traefik]
  command=/usr/local/bin/traefik --configFile=/etc/traefik/traefik.yml
  autostart=true
  autorestart=true
  redirect_stderr=true
  stdout_logfile=/dev/fd/1
  stdout_logfile_maxbytes=0
